# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_BUILDKIT: 1

steps:
- script: |
    export DOCKER_BUILDKIT=1
    docker build --platform=local -o . git://github.com/docker/buildx
    ./buildx build ./src -o type=image,name=your-image --cache-to=type=local,dest=./docker-cache

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: my-image
    command: build
    Dockerfile: src/Dockerfile